# Generated by Django 3.2.6 on 2021-08-17 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dataspoint',
            new_name='Datapoint',
        ),
        migrations.RenameField(
            model_name='datapoint',
            old_name='general_json',
            new_name='data_json',
        ),
    ]
