# Generated by Django 3.2.6 on 2021-08-18 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210817_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 8, 18, 8, 26, 3, 803898)),
            preserve_default=False,
        ),
    ]
